name: Scale Manager Tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
                java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter pub get
      - run: flutter test
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "./coverage/lcov.info"
          min_coverage: 95
          exclude: "**/*_observer.dart **/change.dart"

